name: Cleanup Workflow Runs

on:
  workflow_dispatch:
    inputs:
      clean_success:
        description: '是否清除成功记录'
        required: false
        default: false
        type: boolean
      keep_latest:
        description: '保留最近N条记录（默认0）'
        required: false
        default: 0
        type: number

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 安装 GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: 清理 Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAN_SUCCESS: ${{ github.event.inputs.clean_success }}
          KEEP_LATEST: ${{ github.event.inputs.keep_latest }}
        run: |
          # 设置要清理的状态
          if [ "${CLEAN_SUCCESS}" = "true" ]; then
            STATUS="completed"
          else
            STATUS="failure"
          fi

          REPO="${{ github.repository }}"

          # 获取所有 workflow IDs
          workflows=$(gh workflow list --repo "$REPO" --json id -q '.[] | .id')
          for wf in $workflows; do
            # 获取指定状态的 runs（最新的在最前面）
            runs=$(gh run list --repo "$REPO" --workflow "$wf" --status "$STATUS" --json databaseId -q '.[] | .databaseId')
            count=0
            for run_id in $runs; do
              count=$((count+1))
              if [ "$count" -le "$KEEP_LATEST" ]; then
                continue
              fi
              echo "Deleting run $run_id"
              gh run delete "$run_id" --repo "$REPO" --confirm
            done
          done
