name: Cleanup Workflow Runs

on:
  workflow_dispatch:
    inputs:
      clean_success:
        description: '是否清除成功记录'
        required: false
        default: false
        type: boolean
      keep_latest:
        description: '保留最近N条记录（默认0）'
        required: false
        default: 0
        type: number

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: 清理 Workflow Runs
        env:
          CLEAN_SUCCESS: ${{ github.event.inputs.clean_success }}
          KEEP_LATEST: ${{ github.event.inputs.keep_latest }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取所有 workflow IDs
          workflows=$(gh workflow list --json id -q '.[] | .id')
          for wf in $workflows; do
            # 获取 workflow runs
            if [ "$CLEAN_SUCCESS" = "true" ]; then
              status="completed"
            else
              status="failure"
            fi

            # 获取 runs, 按时间倒序
            runs=$(gh run list --workflow $wf --status $status --json databaseId,status,conclusion,createdAt -q '.[] | .databaseId' | tac)
            count=0
            for run_id in $runs; do
              count=$((count+1))
              if [ "$KEEP_LATEST" -gt 0 ] && [ $count -le $KEEP_LATEST ]; then
                continue
              fi
              echo "Deleting run $run_id"
              gh run delete $run_id --confirm
            done
          done
