name: Auto-update CPU/FEIL options

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 03:12 运行
  workflow_dispatch:

permissions:
  contents: write    # 用于读写工作流外的文件

jobs:
  update-options:
    runs-on: ubuntu-latest

    env:
      WF_FILE: ".github/workflows/Build-SukiSU-Ultra.yml"
      UPSTREAM_REPO: "OnePlusOSS/kernel_manifest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq and yq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          sudo curl -fsSL -o /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Fetch upstream branches -> CPU list
        shell: bash
        run: |
          set -Eeuo pipefail
          # 完整分支名
          git ls-remote --heads https://github.com/${UPSTREAM_REPO}.git \
            | awk '{print $2}' | sed 's#refs/heads/##' > branches_full.txt
          # 取尾部 smXXXX
          awk -F'/' '{print $NF}' branches_full.txt \
            | awk '/^sm[0-9]+$/' | sort -u > cpu_list.txt

      - name: Collect .xml basenames -> FEIL list
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -Eeuo pipefail
          : > xml_names.txt
          while read -r full_branch; do
            ref_enc=${full_branch//\//%2F}
            api=https://api.github.com/repos/${UPSTREAM_REPO}/git/trees/${ref_enc}?recursive=1
            resp=$(curl -sS -H "Accept: application/vnd.github+json" "$api" || true)
            # 只有当 resp.tree 存在时才处理
            if echo "$resp" | jq -e '.tree' >/dev/null 2>&1; then
              echo "$resp" \
                | jq -r '.tree[] | select(.type=="blob" and endswith(.path; ".xml")) | .path' \
                | sed -E 's#.*/##;s/\.xml$//' \
                >> xml_names.txt
            fi
            sleep 0.2
          done < branches_full.txt
          sort -u xml_names.txt -o xml_names.txt

      - name: Update CPU.options in Build-SukiSU-Ultra.yml
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -s cpu_list.txt ] && yq -e '.on.workflow_dispatch.inputs.CPU' "$WF_FILE" >/dev/null; then
            yq -i '.on.workflow_dispatch.inputs.CPU.options = []' "$WF_FILE"
            while read -r soc; do
              yq -i ".on.workflow_dispatch.inputs.CPU.options += [\"$soc\"]" "$WF_FILE"
            done < cpu_list.txt
          fi

      - name: Update FEIL.options in Build-SukiSU-Ultra.yml
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -s xml_names.txt ] && yq -e '.on.workflow_dispatch.inputs.FEIL' "$WF_FILE" >/dev/null; then
            yq -i '.on.workflow_dispatch.inputs.FEIL.options = []' "$WF_FILE"
            while read -r name; do
              yq -i ".on.workflow_dispatch.inputs.FEIL.options += [\"$name\"]" "$WF_FILE"
            done < xml_names.txt
          fi

      - name: Ensure defaults are valid
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -s cpu_list.txt ]; then
            def=$(yq -r '.on.workflow_dispatch.inputs.CPU.default // ""' "$WF_FILE")
            grep -qxF "$def" cpu_list.txt || \
              yq -i ".on.workflow_dispatch.inputs.CPU.default = \"$(head -n1 cpu_list.txt)\"" "$WF_FILE"
          fi
          if [ -s xml_names.txt ]; then
            def=$(yq -r '.on.workflow_dispatch.inputs.FEIL.default // ""' "$WF_FILE")
            grep -qxF "$def" xml_names.txt || \
              yq -i ".on.workflow_dispatch.inputs.FEIL.default = \"$(head -n1 xml_names.txt)\"" "$WF_FILE"
          fi

      - name: Create Pull Request with updates
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore: auto-update CPU and FEIL options
          branch: update-options-${{ github.run_id }}
          title: chore: auto-update CPU and FEIL options from ${UPSTREAM_REPO}
          labels: automated
          paths: .github/workflows/Build-SukiSU-Ultra.yml
