name: Auto-update CPU/FEIL options

on:
  schedule:
    - cron: "12 3 * * *" # 每天 UTC 03:12 运行，可按需调整
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-options:
    runs-on: ubuntu-latest

    env:
      WF_FILE: ".github/workflows/Build-SukiSU-Ultra.yml"
      UPSTREAM_REPO: "OnePlusOSS/kernel_manifest"

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install jq and yq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          sudo curl -fsSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version
          jq --version

      - name: Fetch upstream branches -> CPU list
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          git ls-remote --heads "https://github.com/${UPSTREAM_REPO}.git" \
            | awk -F'/' '{print $NF}' > branches.txt

          # 用 awk 过滤以 sm 开头的 SoC 名称；即使没有匹配也不会非零退出
          awk '/^sm[0-9]+$/' branches.txt | sort -u > cpu_list.txt

          echo "CPU candidates (count: $(wc -l < cpu_list.txt)):"
          head -n 50 cpu_list.txt || true

      - name: Collect all .xml basenames from all branches -> FEIL list
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -Eeuo pipefail
          set -x
          : > xml_names.txt

          while read -r branch; do
            # URL 编码（处理包含斜杠的分支名）
            ref_enc="${branch//\//%2F}"
            api="https://api.github.com/repos/${UPSTREAM_REPO}/git/trees/${ref_enc}?recursive=1"

            if [ -n "${GITHUB_TOKEN:-}" ]; then
              resp="$(curl -sS -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                               -H "Accept: application/vnd.github+json" \
                               "$api" || true)"
            else
              resp="$(curl -sS -H "Accept: application/vnd.github+json" "$api" || true)"
            fi

            # 校验 JSON
            if ! echo "$resp" | jq -e type >/dev/null 2>&1; then
              echo "Skip branch $branch: invalid JSON" >&2
              continue
            fi

            # 仅取 blob 且 .xml 结尾；输出去路径、去后缀的名字
            echo "$resp" \
              | jq -r '(.tree // [])[] | select(.type=="blob" and (.path|endswith(".xml"))) | .path' \
              | sed -E 's#.*/##; s/\.xml$//' \
              >> xml_names.txt || true

            sleep 0.2
          done < branches.txt

          sort -u xml_names.txt -o xml_names.txt

          echo "FEIL candidates (count: $(wc -l < xml_names.txt)):"
          head -n 50 xml_names.txt || true

      - name: Update CPU.options in Build-SukiSU-Ultra.yml
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          test -f "$WF_FILE" || { echo "Workflow file not found: $WF_FILE"; exit 1; }

          if yq -e '.on.workflow_dispatch.inputs.CPU' "$WF_FILE" >/dev/null 2>&1; then
            if [ -s cpu_list.txt ]; then
              yq -i '.on.workflow_dispatch.inputs.CPU.options = []' "$WF_FILE"
              while read -r soc; do
                [ -n "$soc" ] && yq -i ".on.workflow_dispatch.inputs.CPU.options += [\"${soc}\"]" "$WF_FILE"
              done < cpu_list.txt
              echo "Updated CPU.options:"
              yq '.on.workflow_dispatch.inputs.CPU.options' "$WF_FILE" || true
            else
              echo "cpu_list.txt is empty; skip updating CPU.options to avoid clearing existing options."
            fi
          else
            echo "CPU input not found in $WF_FILE, skipped."
          fi

      - name: Update FEIL.options in Build-SukiSU-Ultra.yml
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          if yq -e '.on.workflow_dispatch.inputs.FEIL' "$WF_FILE" >/dev/null 2>&1; then
            if [ -s xml_names.txt ]; then
              yq -i '.on.workflow_dispatch.inputs.FEIL.options = []' "$WF_FILE"
              while read -r name; do
                [ -n "$name" ] && yq -i ".on.workflow_dispatch.inputs.FEIL.options += [\"${name}\"]" "$WF_FILE"
              done < xml_names.txt
              echo "Updated FEIL.options:"
              yq '.on.workflow_dispatch.inputs.FEIL.options' "$WF_FILE" || true
            else
              echo "xml_names.txt is empty; skip updating FEIL.options to avoid clearing existing options."
            fi
          else
            echo "FEIL input not found in $WF_FILE, skipped."
          fi

      - name: Ensure defaults are valid (optional)
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          # CPU default
          if [ -s cpu_list.txt ]; then
            cpu_default="$(yq -r '.on.workflow_dispatch.inputs.CPU.default // ""' "$WF_FILE")"
            if [ -n "$cpu_default" ] && ! grep -qx "$cpu_default" cpu_list.txt; then
              new_default="$(head -n1 cpu_list.txt || true)"
              if [ -n "$new_default" ]; then
                yq -i ".on.workflow_dispatch.inputs.CPU.default = \"$new_default\"" "$WF_FILE"
              fi
            fi
          fi

          # FEIL default
          if [ -s xml_names.txt ]; then
            feil_default="$(yq -r '.on.workflow_dispatch.inputs.FEIL.default // ""' "$WF_FILE")"
            if [ -n "$feil_default" ] && ! grep -qx "$feil_default" xml_names.txt; then
              new_default="$(head -n1 xml_names.txt || true)"
              if [ -n "$new_default" ]; then
                yq -i ".on.workflow_dispatch.inputs.FEIL.default = \"$new_default\"" "$WF_FILE"
              fi
            fi
          fi

      - name: Commit and push if changed
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          if git status --porcelain | grep -q .; then
            git config user.name "FurLC"
            git config user.email "qq441791056@163.com"
            git add "$WF_FILE"
            git commit -m "chore: auto-update CPU and FEIL options from ${UPSTREAM_REPO}"
            git push
          else
            echo "No changes to commit."
          fi
