name: Auto-update CPU/FEIL options

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-options:
    runs-on: ubuntu-latest

    env:
      WF_FILE: ".github/workflows/Build-SukiSU-Ultra.yml"
      UPSTREAM_REPO: "OnePlusOSS/kernel_manifest"

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          set -Eeuo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq curl
          curl -fsSL \
            "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" \
            -o /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq

      - name: Generate CPU & FEIL lists
        shell: bash
        run: |
          set -Eeuo pipefail
          # 1) 拉取所有分支
          git ls-remote --heads "https://github.com/${UPSTREAM_REPO}.git" \
            | sed 's#refs/heads/##' > branches.txt

          # 2) CPU 列表（只保留 sm + 数字）
          grep -E 'sm[0-9]+' branches.txt | sed 's#.*/##' | sort -u > cpu_list.txt

          # 3) FEIL 列表（收集 .xml 文件名，不含后缀）
          : > xml_names.txt
          while read -r b; do
            ref_enc=${b//\//%2F}
            api="https://api.github.com/repos/${UPSTREAM_REPO}/git/trees/${ref_enc}?recursive=1"
            curl -sS -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                     -H "Accept: application/vnd.github+json" \
                     "$api" \
              | jq -r '(.tree // [])[] 
                        | select(.type=="blob" and (.path|endswith(".xml")))
                        | .path' \
              | xargs -n1 basename -s .xml >> xml_names.txt
            sleep 0.2
          done < branches.txt

          sort -u xml_names.txt -o xml_names.txt

      - name: Update workflow_dispatch inputs
        shell: bash
        run: |
          set -Eeuo pipefail
          for NAME in CPU FEIL; do
            LIST_FILE="${NAME,,}_list.txt"
            # 清空 options
            yq eval -i ".on.workflow_dispatch.inputs.${NAME}.options = []" "$WF_FILE"

            # 重新填充 options
            if [ -s "$LIST_FILE" ]; then
              while read -r item; do
                yq eval -i ".on.workflow_dispatch.inputs.${NAME}.options += [\"${item}\"]" "$WF_FILE"
              done < "$LIST_FILE"
            fi

            # 校验并更新 default
            DEF_PATH=".on.workflow_dispatch.inputs.${NAME}.default"
            CUR=$(yq eval -r "${DEF_PATH} // \"\"" "$WF_FILE")
            if ! grep -qxF "$CUR" "$LIST_FILE"; then
              NEW=$(head -n1 "$LIST_FILE")
              [ -n "$NEW" ] && yq eval -i "${DEF_PATH} = \"${NEW}\"" "$WF_FILE"
            fi
          done

      - name: Commit & push if changed
        shell: bash
        run: |
          set -Eeuo pipefail
          # 如果没有变更就退出
          git diff --quiet || {
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$WF_FILE"
            git commit -m "chore: auto-update CPU and FEIL options"
            git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
            git push origin HEAD:main
          }
