name: 自动刷新 FEIL 配置 options

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-feil-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 本仓库
        uses: actions/checkout@v4

      - name: 安装 jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: 获取所有分支名
        run: |
          git ls-remote --heads https://github.com/OnePlusOSS/kernel_manifest.git | awk -F'/' '{print $NF}' > branch_list.txt

      - name: 获取所有分支下的 .xml 文件名
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          > feil_options.txt
          while read branch; do
            # 拉取分支下根目录所有文件
            files=$(curl -s "https://api.github.com/repos/OnePlusOSS/kernel_manifest/contents?ref=$branch" | jq -r '.[] | select(.name | endswith(".xml")) | .name')
            for f in $files; do
              name="${f%.xml}"
              echo "$name" >> feil_options.txt
            done
          done < branch_list.txt
          # 去重排序
          sort -u feil_options.txt -o feil_options.txt

      - name: 生成新的 config.yaml
        run: |
          echo "FEIL:" > config.yaml
          echo "  description: \"配置文件\"" >> config.yaml
          echo "  type: choice" >> config.yaml
          echo "  required: true" >> config.yaml
          # 默认值可自行调整
          echo "  default: oneplus_ace3_v" >> config.yaml
          echo "  options:" >> config.yaml
          while read name; do
            echo "    - $name" >> config.yaml
          done < feil_options.txt

      - name: 提交并推送更新
        run: |
          git config --global user.email "11441791056@163.com"
          git config --global user.name "FurLC"
          git add config.yaml
          git commit -m "自动刷新 FEIL 配置 options"
          git push
