name: Auto-update CPU/FEIL options

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-options:
    runs-on: ubuntu-latest
    env:
      WF_FILE: ".github/workflows/Build-SukiSU-Ultra.yml"
      UPSTREAM_REPO: "OnePlusOSS/kernel_manifest"

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          set -Eeuo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq repo

      - name: Generate CPU & FEIL lists
        run: |
          set -Eeuo pipefail
          git ls-remote --heads "https://github.com/${UPSTREAM_REPO}.git" \
            | sed 's#refs/heads/##' > branches.txt
          grep -E 'sm[0-9]+' branches.txt | sed 's#.*/##' | sort -u > cpu_list.txt

          : > xml_names.txt
          while IFS= read -r branch; do
            [[ -z "$branch" ]] && continue
            ref_enc=${branch//\//%2F}
            [[ -z "$ref_enc" ]] && continue
            resp=$(curl -sS -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                       -H "Accept: application/vnd.github+json" \
                       "https://api.github.com/repos/${UPSTREAM_REPO}/git/trees/${ref_enc}?recursive=1" \
                      || true)
            jq -r '(.tree//[])[]
                   | select(.type=="blob" and .path|endswith(".xml"))
                   | .path' <<<"$resp" \
              | xargs -n1 basename -s .xml >> xml_names.txt
            sleep 0.2
          done < branches.txt
          sort -u xml_names.txt -o xml_names.txt

      - name: Replace CPU options in workflow
        run: |
          set -Eeuo pipefail
          # build a replacement block for CPU
          {
            echo "# CPU_OPTIONS_START"
            echo "options:"
            while IFS= read -r soc; do
              echo "  - $soc"
            done < cpu_list.txt
            echo "# CPU_OPTIONS_END"
          } > cpu_block.txt

          # in-place replace between markers
          sed -i "/# CPU_OPTIONS_START/,/# CPU_OPTIONS_END/{ 
            /# CPU_OPTIONS_START/{p; r cpu_block.txt
            }; 
            /# CPU_OPTIONS_END/p; 
            d 
          }" "$WF_FILE"

      - name: Replace FEIL options in workflow
        run: |
          set -Eeuo pipefail
          # build a replacement block for FEIL
          {
            echo "# FEIL_OPTIONS_START"
            echo "options:"
            while IFS= read -r xml; do
              echo "  - $xml"
            done < xml_names.txt
            echo "# FEIL_OPTIONS_END"
          } > feil_block.txt

          sed -i "/# FEIL_OPTIONS_START/,/# FEIL_OPTIONS_END/{ 
            /# FEIL_OPTIONS_START/{p; r feil_block.txt
            }; 
            /# FEIL_OPTIONS_END/p; 
            d 
          }" "$WF_FILE"

      - name: Commit & push if changed
        run: |
          set -Eeuo pipefail
          git diff --quiet || {
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$WF_FILE"
            git commit -m "chore: update CPU and FEIL options"
            git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          }
